### ISSUE TITLE
Image Caption & Image position

### ISSUE THREAD

**Issue by GPVnRT** [bicarlsen/obsidian_image_caption#31]
# Hey

Your extension is great, but I can't use it in combination with my CSS snippet that put the image either on Left/Center/Right side. 

I put there my CSS snippet that I use for that purpose that is being replaced by your extension. 

I found it there: https://forum.obsidian.md/t/align-image/78050
Made by Gautamneeraj

# Image position CSS snippet

```css
img[alt*="center"] {
    display: block;
    margin-left: auto;
    margin-right: auto;
}

img[alt*="right"] {
    float: right;
    clear: right;
    margin-left: 1rem;
    margin-bottom: 2px;
    margin-top: 2px;
}
```

# May be 
I'm not mastering at all your extension, but could it be possible to add that functionality (positioning image) at the same time than adding image caption? 

It would be great, thanks! 

Gautier
